# -*- coding: utf-8 -*-
"""InformeProyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13X0A6sLzUTuRALHigywu-uvle7HnO5kO

# Distribución Cuadricula
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as patches
import numpy as np
import os

# CONFIGURACIÓN DE DIRECTORIOS
# Esto crea la carpeta 'output' automáticamente al ejecutar el script
if not os.path.exists('output'):
    os.makedirs('output')
    print("✅ Carpeta 'output' creada exitosamente.")

# --- 1. CONFIGURACIÓN Y CARGA DE DATOS (ETL) ---
# Aquí continúa su código original (plt.rcParams, try/except, etc.)

# --- 1. CONFIGURACIÓN Y CARGA DE DATOS (ETL) ---
# Configuración de estilos globales para matplotlib
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Liberation Sans']

# Detección de ruta
try:
    user_home = os.path.expanduser("~")
    file_path = os.path.join(user_home, "Downloads", "Detalle_CurvaS_Subestacion.xlsx")
    if not os.path.exists(file_path):
        file_path = "Detalle_CurvaS_Subestacion.xlsx"
    print(f"📂 Leyendo: {file_path}")

    # Read Excel without header to manually set column names
    df_raw_fases = pd.read_excel(file_path, sheet_name='Detalle_Fases', header=None)
    df_raw_curva = pd.read_excel(file_path, sheet_name='Datos_Curva_S', header=None)

    # Process df_raw_fases
    # Find the row containing 'Tipo_Dato' to use as header
    header_row_index_fases = -1
    for i in range(df_raw_fases.shape[0]):
        if 'Tipo_Dato' in df_raw_fases.iloc[i].astype(str).values:
            header_row_index_fases = i
            break

    if header_row_index_fases == -1:
        raise ValueError("Could not find 'Tipo_Dato' column in 'Detalle_Fases' sheet headers.")

    new_columns_fases = df_raw_fases.iloc[header_row_index_fases].values
    df_raw_fases.columns = [str(col).strip() for col in new_columns_fases] # Clean column names
    df_raw_fases = df_raw_fases[header_row_index_fases + 1:].reset_index(drop=True) # Drop header and all rows above it
    df_raw_fases = df_raw_fases.loc[:, df_raw_fases.columns != 'nan'] # Drop columns explicitly named 'nan'

    # Process df_raw_curva
    # Find the row containing 'PV (Planificado)' to use as header
    header_row_index_curva = -1
    for i in range(df_raw_curva.shape[0]):
        if 'PV (Planificado)' in df_raw_curva.iloc[i].astype(str).values:
            header_row_index_curva = i
            break

    if header_row_index_curva == -1:
        raise ValueError("Could not find 'PV (Planificado)' column in 'Datos_Curva_S' sheet headers.")

    new_columns_curva = df_raw_curva.iloc[header_row_index_curva].values
    df_raw_curva.columns = [str(col).strip() for col in new_columns_curva]
    df_raw_curva = df_raw_curva[header_row_index_curva + 1:].reset_index(drop=True)
    df_raw_curva = df_raw_curva.loc[:, df_raw_curva.columns != 'nan']

    # Convert relevant columns to numeric after loading and cleaning headers
    numeric_cols_fases = ['Total'] + [col for col in df_raw_fases.columns if 'Mes' in col]
    for col in numeric_cols_fases:
        if col in df_raw_fases.columns:
            df_raw_fases[col] = pd.to_numeric(df_raw_fases[col], errors='coerce')

    numeric_cols_curva = ['AC (Costo Real)', 'EV (Valor Ganado)', 'PV (Planificado)', 'PV_Acum', 'EV_Acum', 'AC_Acum']
    for col in numeric_cols_curva:
        if col in df_raw_curva.columns:
            df_raw_curva[col] = pd.to_numeric(df_raw_curva[col], errors='coerce')

except FileNotFoundError:
    print("❌ Error: Sube el archivo 'Detalle_CurvaS_Subestacion.xlsx'.")
    raise

# --- 2. PROCESAMIENTO DE DATOS (PMP ENGINE) ---
# A. Tabla Maestra de Fases
df_pv = df_raw_fases[df_raw_fases['Tipo_Dato'].str.contains('PV')][['Fase', 'Total']].rename(columns={'Total': 'BAC'})
df_ev = df_raw_fases[df_raw_fases['Tipo_Dato'].str.contains('EV')][['Fase', 'Total']].rename(columns={'Total': 'EV'})
df_ac = df_raw_fases[df_raw_fases['Tipo_Dato'].str.contains('AC')][['Fase', 'Total']].rename(columns={'Total': 'AC'})
df = df_pv.merge(df_ev, on='Fase').merge(df_ac, on='Fase')

# Calcular PV al Corte (Mes 6)
cols_meses = [c for c in df_raw_fases.columns if 'Mes' in str(c)] # Convert column name to string before 'in'
meses_corte = cols_meses[:6]
df_raw_fases['PV_Corte'] = df_raw_fases[meses_corte].sum(axis=1)
df_pv_corte = df_raw_fases[df_raw_fases['Tipo_Dato'].str.contains('PV')][['Fase', 'PV_Corte']].rename(columns={'PV_Corte': 'PV'})
df = df.drop(columns=['PV'], errors='ignore').merge(df_pv_corte, on='Fase')

# Cálculos EVM
df['CV'] = df['EV'] - df['AC']
df['SV'] = df['EV'] - df['PV']
df['CPI'] = df.apply(lambda x: x['EV'] / x['AC'] if x['AC'] > 0 else 1.0, axis=1)
df['SPI'] = df.apply(lambda x: x['EV'] / x['PV'] if x['PV'] > 0 else 1.0, axis=1)
df['EAC'] = df.apply(lambda x: x['BAC'] / x['CPI'] if x['CPI'] > 0 else x['BAC'], axis=1)
df['VAC'] = df['BAC'] - df['EAC']

# Crear etiquetas cortas para gráficos (ej: F1, F2...)
df['Label'] = df['Fase'].apply(lambda x: x.split('.')[0])

# B. Datos Históricos
df_hist = df_raw_curva.dropna(subset=['EV (Valor Ganado)']).copy()
df_hist['CPI_Hist'] = df_hist['EV (Valor Ganado)'] / df_hist['AC (Costo Real)']
df_hist['SPI_Hist'] = df_hist['EV (Valor Ganado)'] / df_hist['PV (Planificado)']

# C. Totales Globales
tot_bac = df['BAC'].sum()
tot_ev = df['EV'].sum()
tot_ac = df['AC'].sum()
tot_pv = df['PV'].sum()
tot_eac = df['EAC'].sum()
tot_vac = df['VAC'].sum()
global_cpi = tot_ev / tot_ac if tot_ac > 0 else 1.0
global_spi = tot_ev / tot_pv if tot_pv > 0 else 1.0

# --- 3. CONSTRUCCIÓN DEL DASHBOARD (REPLICA EXACTA) ---
# Colores de la referencia
c_header_bg = '#003366'  # Azul oscuro institucional
c_table_header = '#212121'  # Gris casi negro
c_bar_blue = '#1976D2'
c_bar_orange = '#FF9800'
c_line_blue = '#0288D1'
c_line_orange = '#F57C00'
c_zone_red = '#FFEBEE'  # Fondo rojo muy suave
c_zone_green = '#E8F5E9'  # Fondo verde muy suave

fig = plt.figure(figsize=(20, 11))

# Definición de la Rejilla (GridSpec)
# 4 Filas: Header, Top Row (2 quadrants), Bottom Row (2 quadrants), Footer
# 4 Columnas: Margin (1cm), Left (35%), Right (35%), Report (30%)
gs = gridspec.GridSpec(4, 4,
                       height_ratios=[0.06, 0.47, 0.47, 0.06],
                       width_ratios=[0.05, 0.335, 0.335, 0.28])

# Ajustes de espaciado uniforme
plt.subplots_adjust(left=0.02, right=0.98, top=0.97, bottom=0.03, wspace=0.18, hspace=0.28)

# --- A. ENCABEZADO (HEADER) ---
ax_header = fig.add_subplot(gs[0, :])
ax_header.axis('off')
rect = patches.Rectangle((0, 0), 1, 1, transform=ax_header.transAxes, color=c_header_bg, zorder=0)
ax_header.add_patch(rect)
ax_header.text(0.02, 0.5, "Informe Ejecutivo por Proyecto", color='white', fontsize=22, fontweight='bold', va='center')

# --- B. TABLA (TOP LEFT QUADRANT) ---
ax_table = fig.add_subplot(gs[1, 1])
ax_table.axis('off')

cols = ['Fase', 'BAC', 'PV', 'EV', 'AC', 'CV', 'SPI', 'CPI', 'EAC']
cell_data = []
for i, row in df.iterrows():
    cell_data.append([
        row['Fase'],
        f"{row['BAC']:,.0f}", f"{row['PV']:,.0f}", f"{row['EV']:,.0f}", f"{row['AC']:,.0f}",
        f"{row['CV']:,.0f}", f"{row['SPI']:.2f}", f"{row['CPI']:.2f}", f"{row['EAC']:,.0f}"
    ])

# Añadir título como texto separado (sin negrilla)
ax_table.text(0.5, 1.0, "ESTADO DETALLADO POR FASES", fontsize=9,
              ha='center', va='top', transform=ax_table.transAxes)

# Crear tabla expandida al máximo
table = ax_table.table(cellText=cell_data, colLabels=cols, cellLoc='center', loc='center',
                        bbox=[0, 0, 1, 0.96])
table.auto_set_font_size(False)
table.set_fontsize(6.5)
table.scale(1, 2.0)
table.auto_set_column_width(col=list(range(len(cols))))

# Estilizado de Tabla (Replica Referencia)
for (row, col), cell in table.get_celld().items():
    cell.set_edgecolor('gray')
    cell.set_linewidth(0.5)
    if row == 0:  # Header
        cell.set_text_props(weight='bold', color='white')
        cell.set_facecolor(c_table_header)
    else:
        # Alinear columna 'Fase' a la izquierda
        if col == 0:
            cell.set_text_props(ha='left')

        # Colores condicionales para SPI (col 6) y CPI (col 7)
        val_spi = float(cell_data[row-1][6])
        val_cpi = float(cell_data[row-1][7])
        if col == 6:  # SPI
            if val_spi < 0.85: cell.set_facecolor('#FFCDD2')  # Rojo claro
            elif val_spi < 0.98: cell.set_facecolor('#FFF9C4')  # Amarillo claro
            else: cell.set_facecolor('#C8E6C9')  # Verde claro
        elif col == 7:  # CPI
            if val_cpi < 0.85: cell.set_facecolor('#FFCDD2')
            elif val_cpi < 0.98: cell.set_facecolor('#FFF9C4')
            else: cell.set_facecolor('#C8E6C9')
        else:
            cell.set_facecolor('white')

# --- C. TEXTO DERECHA (RIGHT COLUMN - SPANNING ALL QUADRANTS) ---
ax_text = fig.add_subplot(gs[1:3, 3])
ax_text.axis('off')

# Generar texto dinámico
fase_critica = df.loc[df['CV'].idxmin()]
txt_report = (
    f"INFORME EJECUTIVO FINAL - PROYECTO SUBESTACIÓN 10MVA\n"
    f"=====================================================\n\n"
    f"1. RESULTADOS GLOBALES:\n"
    f"----------------------\n"
    f"  - Presupuesto Original (BAC): ${tot_bac:,.0f}\n"
    f"  - Estimado al Cierre (EAC): ${tot_eac:,.0f}\n"
    f"  - Variación Final (VAC): ${tot_vac:,.0f}\n"
    f"  - Índice Eficiencia Costo: {global_cpi:.2f}\n\n"
    f"2. ANÁLISIS DE CAUSA RAÍZ (FASES CRÍTICAS):\n"
    f"------------------------------------------\n"
    f"  La fase '{fase_critica['Label']}' presenta la mayor\n"
    f"  desviación negativa (${fase_critica['CV']:,.0f}).\n\n"
    f"  Hallazgos:\n"
    f"  - El CPI de {fase_critica['CPI']:.2f} indica que por cada\n"
    f"    dólar invertido, solo se genera ${fase_critica['CPI']:.2f}.\n"
    f"  - Tendencia: El gráfico histórico muestra una\n"
    f"    caída sostenida del rendimiento desde el Mes 3.\n\n"
    f"3. RECOMENDACIONES ESTRATÉGICAS:\n"
    f"--------------------------------\n"
    f"  A. ACCIÓN INMEDIATA (CORTO PLAZO):\n"
    f"    - Realizar auditoría de rendimientos en {fase_critica['Label']}.\n"
    f"    - Congelar cambios de alcance.\n\n"
    f"  B. GESTIÓN CONTRACTUAL:\n"
    f"    - Revisar cláusulas de penalización.\n"
    f"    - Evaluar recuperación de cronograma (Crashing).\n\n"
    f"  C. PROYECCIÓN:\n"
    f"    - De mantenerse la tendencia, se requerirá\n"
    f"      una inyección de capital de aprox. ${abs(tot_vac):,.0f}."
)

ax_text.text(0.05, 1.0, txt_report, fontsize=9, family='monospace', va='top', linespacing=1.4)

# --- D. GRÁFICO DE LÍNEAS (TOP RIGHT QUADRANT - EVOLUCIÓN) ---
ax_line = fig.add_subplot(gs[1, 2])

# Zona crítica inferior
ax_line.axhspan(0.7, 0.9, color=c_zone_red, alpha=0.5, label='Zona Crítica')
ax_line.plot(df_hist['Mes'], df_hist['CPI_Hist'], marker='o', color=c_line_blue, label='CPI (Eficiencia Costo)', linewidth=2.5, markersize=6)
ax_line.plot(df_hist['Mes'], df_hist['SPI_Hist'], marker='s', color=c_line_orange, label='SPI (Eficiencia Cronograma)', linewidth=2.5, markersize=6)
ax_line.axhline(1.0, color='#4CAF50', linestyle='--', label='Línea Base (1.0)', linewidth=1.5)

ax_line.set_title("EVOLUCIÓN HISTÓRICA DE ÍNDICES DEL PROYECTO", fontsize=9, pad=8)
ax_line.set_ylim(0.7, 1.25)
ax_line.legend(loc='lower left', ncol=1, fontsize=7.5)
ax_line.grid(True, linestyle=':', alpha=0.6)
ax_line.tick_params(axis='both', labelsize=8)

# --- E. GRÁFICO DE BURBUJAS (BOTTOM LEFT QUADRANT - MAPA) ---
ax_bub = fig.add_subplot(gs[2, 1])
# Zonas de fondo
ax_bub.axvspan(0, 1, ymin=0, ymax=1, color=c_zone_red, alpha=0.5)
ax_bub.axvspan(1, 1.4, ymin=0, ymax=1, color='white', alpha=0.5)

# Burbujas
colors_bub = ['#D32F2F' if (r['CPI']<0.9 or r['SPI']<0.9) else '#388E3C' for i, r in df.iterrows()]
sizes = df['BAC'] / 500
ax_bub.scatter(df['SPI'], df['CPI'], s=sizes, c=colors_bub, edgecolors='black', alpha=0.7, zorder=3)

# Etiquetas
for i, row in df.iterrows():
    ax_bub.text(row['SPI'], row['CPI'], row['Label'], fontsize=7, ha='center', va='center', color='white', weight='bold')

ax_bub.set_title("MAPA DE DESEMPEÑO (BURBUJAS)", fontsize=9, weight='normal')
ax_bub.set_xlabel("SPI (Tiempo)", fontsize=8)
ax_bub.set_ylabel("CPI (Costo)", fontsize=8)
ax_bub.axhline(1, color='gray', linestyle='--', linewidth=1)
ax_bub.axvline(1, color='gray', linestyle='--', linewidth=1)
ax_bub.set_xlim(0.6, 1.3); ax_bub.set_ylim(0.6, 1.3)
ax_bub.grid(True, linestyle=':', alpha=0.5)
ax_bub.tick_params(axis='both', labelsize=7)

# --- F. GRÁFICO DE BARRAS (BOTTOM RIGHT QUADRANT - ANÁLISIS) ---
ax_bar = fig.add_subplot(gs[2, 2])
y_pos = np.arange(len(df))
width = 0.4

# Barras horizontales
rects1 = ax_bar.barh(y_pos + width/2, df['CV'], width, label='Costo Variance (CV)', color=c_bar_blue)
rects2 = ax_bar.barh(y_pos - width/2, df['SV'], width, label='Schedule Variance (SV)', color=c_bar_orange)

ax_bar.set_yticks(y_pos)
ax_bar.set_yticklabels(df['Label'])
ax_bar.invert_yaxis()
ax_bar.axvline(0, color='black', linewidth=1.2)
ax_bar.set_title("ANÁLISIS DE VARIANZA FINANCIERA (CV VS SV)", fontsize=9, pad=8)
ax_bar.legend(loc='upper left', fontsize=7.5)
ax_bar.grid(axis='x', linestyle=':', alpha=0.5)
ax_bar.tick_params(axis='x', labelsize=8)
ax_bar.tick_params(axis='y', labelsize=8)

# --- G. FOOTER (Pie de Página) ---
ax_foot = fig.add_subplot(gs[3, :])
ax_foot.axis('off')
rect_f = patches.Rectangle((0, 0), 1, 1, transform=ax_foot.transAxes, color=c_header_bg, zorder=0)
ax_foot.add_patch(rect_f)
ax_foot.text(0.02, 0.5, "EMILIO PALACÍN GÓMEZ", color='white', fontsize=14, fontweight='bold', va='center')
ax_foot.text(0.5, 0.5, "Consultor PMO | Project Manager PMP® | BI, Reporting Ejecutivo y Control de Proyectos",
             color='white', fontsize=11, va='center', ha='center')
ax_foot.text(0.98, 0.5, "www.linkedin.com/in/emiliopalacin", color='white', fontsize=11, va='center', ha='right')

plt.show()
